import re

with open('client/src/App.tsx', 'r') as f:
    text = f.read()

export_fn = """                const handleExportCode = () => {
                  if (!results || results.task_type !== 'SUPERVISED') return;
                  
                  const target = Object.keys(results.preprocessing?.eda?.features || {}).length > 0 ? "TARGET_COLUMN" : "target";
                  const bestModelStr = bestModel || 'random_forest';
                  
                  const pyCode = `# Auto-generated by ML Studio
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier

# 1. Load Data
df = pd.read_csv('your_dataset.csv')
X = df.drop(columns=['${target}'])
y = df['${target}']

# 2. Identify Column Types
num_cols = X.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = X.select_dtypes(exclude=[np.number]).columns.tolist()

# 3. Build Preprocessor
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])
cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])
preprocessor = ColumnTransformer([
    ('num', num_pipeline, num_cols),
    ('cat', cat_pipeline, cat_cols)
], remainder='drop')

# 4. Build Model Pipeline
# Note: In ML Studio, we dynamically tune models using GridSearchCV.
# Here we export the base pipeline structure for ${bestModelStr.replace('_', ' ')}.
model = RandomForestClassifier(n_estimators=50, random_state=42)

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', model)
])

# 5. Train & Evaluate
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
pipeline.fit(X_train, y_train)

accuracy = pipeline.score(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")
`;
                  
                  const blob = new Blob([pyCode], { type: 'text/plain' });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement('a');
                  a.href = url;
                  a.download = 'ml_studio_pipeline.py';
                  document.body.appendChild(a);
                  a.click();
                  document.body.removeChild(a);
                  URL.revokeObjectURL(url);
                };"""

old_block = """                const colCount = results.preprocessing?.original_shape?.[1] || 0;

                return (
                  <>
                    {/* Stat Cards */}
                    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">"""

new_block = """                const colCount = results.preprocessing?.original_shape?.[1] || 0;

""" + export_fn + """

                return (
                  <>
                    {/* Stat Cards */}
                    <div className="flex justify-between items-end mb-4">
                      <h2 className="text-xl font-bold text-gray-800 dark:text-gray-100 flex items-center gap-2"><Target className="text-emerald-500" /> Pipeline Results</h2>
                      <button onClick={handleExportCode} className="flex items-center gap-2 px-4 py-2 bg-gray-800 hover:bg-gray-700 text-white text-sm font-medium rounded-lg transition-colors shadow-sm cursor-pointer z-50 relative">
                        <Download size={16} /> Export to Python
                      </button>
                    </div>
                    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">"""

text = text.replace(old_block, new_block)

text = text.replace("Brain, FlaskConical, Sparkles", "Brain, FlaskConical, Sparkles, Download")

with open('client/src/App.tsx', 'w') as f:
    f.write(text)

